/**
 * Search vocabulary, so the catalogue answers in more than English.
 *
 * The index holds English words, because that is what Commons file names
 * and our own category list are written in. Typing the Indonesian for
 * library returned nothing at all — not a missing feature so much as a
 * broken promise, since the interface itself speaks eighteen languages.
 *
 * Deliberately a backdrop vocabulary rather than a dictionary: the nouns
 * that name a place, a material or a colour, in the seventeen non-English
 * languages the interface offers. A word claimed by two concepts maps to
 * both, and the search treats them as alternatives.
 *
 * Generated and checked in. A lookup table has no business being built at
 * runtime on the phones this product exists to support.
 */

/** A typed word, lower-cased, to the English the index understands. */
export const VOCAB: Record<string, string[]> = {
  "abu": ["grey"],
  "abu-abu": ["grey"],
  "acantilado": ["cliff"],
  "acik": ["light"],
  "agac": ["tree"],
  "ahsap": ["wood"],
  "ahşap": ["wood"],
  "air terjun": ["waterfall"],
  "alba": ["sunrise"],
  "albero": ["tree"],
  "amanecer": ["sunrise"],
  "amarelo": ["yellow"],
  "amarillo": ["yellow"],
  "arancione": ["orange"],
  "arbol": ["tree"],
  "arbre": ["tree"],
  "arvore": ["tree"],
  "atardecer": ["sunset"],
  "atelier": ["studio"],
  "aube": ["sunrise"],
  "aula": ["classroom"],
  "awan": ["cloud"],
  "azul": ["blue"],
  "açık": ["light"],
  "ağaç": ["tree"],
  "backstein": ["brick"],
  "bahce": ["garden"],
  "bahnhof": ["station"],
  "bahçe": ["garden"],
  "bai bien": ["beach"],
  "baksteen": ["brick"],
  "bamboe": ["bamboo"],
  "bambou": ["bamboo"],
  "bambu": ["bamboo"],
  "bambus": ["bamboo"],
  "bambù": ["bamboo"],
  "bambú": ["bamboo"],
  "bandar": ["city"],
  "bao tang": ["museum"],
  "bata": ["brick"],
  "batu": ["stone"],
  "batu bata": ["brick"],
  "bau troi": ["sky"],
  "baum": ["tree"],
  "benteng": ["castle"],
  "berg": ["mountain"],
  "beyaz": ["white"],
  "bianco": ["white"],
  "biblioteca": ["library"],
  "bibliotheek": ["library"],
  "bibliothek": ["library"],
  "bibliotheque": ["library"],
  "bibliothèque": ["library"],
  "bien": ["sea"],
  "bilik": ["room"],
  "bilik darjah": ["classroom"],
  "bilik tidur": ["bedroom"],
  "binh minh": ["sunrise"],
  "bintang": ["star"],
  "biru": ["blue"],
  "biển": ["sea"],
  "blanc": ["white"],
  "blanco": ["white"],
  "blau": ["blue"],
  "blauw": ["blue"],
  "bleu": ["blue"],
  "bloem": ["flower"],
  "blu": ["blue"],
  "blume": ["flower"],
  "bois": ["wood"],
  "boom": ["tree"],
  "bos": ["forest"],
  "bosco": ["forest"],
  "bosque": ["forest"],
  "branco": ["white"],
  "braun": ["brown"],
  "brique": ["brick"],
  "brucke": ["bridge"],
  "brug": ["bridge"],
  "bruin": ["brown"],
  "brun": ["brown"],
  "brücke": ["bridge"],
  "buluh": ["bamboo"],
  "bulut": ["cloud"],
  "bunga": ["flower"],
  "bureau": ["office"],
  "burg": ["castle"],
  "buro": ["office"],
  "buzul": ["glacier"],
  "bãi biển": ["beach"],
  "bình minh": ["sunrise"],
  "büro": ["office"],
  "bảo tàng": ["museum"],
  "bầu trời": ["sky"],
  "cachoeira": ["waterfall"],
  "cam": ["orange"],
  "camera da letto": ["bedroom"],
  "cami": ["mosque"],
  "camino": ["road"],
  "campo": ["field"],
  "candi": ["temple"],
  "cang": ["harbour"],
  "canh dong": ["field"],
  "carretera": ["road"],
  "cascada": ["waterfall"],
  "cascade": ["waterfall"],
  "cascata": ["waterfall"],
  "castello": ["castle"],
  "castelo": ["castle"],
  "castillo": ["castle"],
  "cau": ["bridge"],
  "cau thang": ["stairs"],
  "caverna": ["cave"],
  "cay": ["tree"],
  "cerah": ["light"],
  "ceu": ["sky"],
  "chambre": ["bedroom"],
  "champ": ["field"],
  "chateau": ["castle"],
  "chiaro": ["light"],
  "chiesa": ["church"],
  "chua": ["temple"],
  "chuyen mau": ["gradient"],
  "chuyển màu": ["gradient"],
  "château": ["castle"],
  "chùa": ["temple"],
  "cicek": ["flower"],
  "cidade": ["city"],
  "ciel": ["sky"],
  "cielo": ["sky"],
  "cinza": ["grey"],
  "citta": ["city"],
  "città": ["city"],
  "ciudad": ["city"],
  "clair": ["light"],
  "claro": ["light"],
  "cocina": ["kitchen"],
  "cokelat": ["brown"],
  "coklat": ["brown"],
  "col": ["desert"],
  "cong vien": ["park"],
  "cortina": ["curtain"],
  "coucher de soleil": ["sunset"],
  "cozinha": ["kitchen"],
  "cucina": ["kitchen"],
  "cueva": ["cave"],
  "cuisine": ["kitchen"],
  "cánh đồng": ["field"],
  "cây": ["tree"],
  "céu": ["sky"],
  "công viên": ["park"],
  "cảng": ["harbour"],
  "cầu": ["bridge"],
  "cầu thang": ["stairs"],
  "da": ["stone"],
  "da cam thach": ["marble"],
  "dag": ["mountain"],
  "dal": ["valley"],
  "danau": ["lake"],
  "dapur": ["kitchen"],
  "dağ": ["mountain"],
  "degradado": ["gradient"],
  "degrade": ["gradient"],
  "dem": ["night"],
  "den": ["black", "temple"],
  "deniz": ["sea"],
  "deniz feneri": ["lighthouse"],
  "desert": ["desert"],
  "deserto": ["desert"],
  "desierto": ["desert"],
  "dinding": ["wall"],
  "do": ["red"],
  "doku": ["texture"],
  "donker": ["dark"],
  "dormitorio": ["bedroom"],
  "doux": ["soft"],
  "dunkel": ["dark"],
  "duong": ["road"],
  "duvar": ["wall"],
  "dégradé": ["gradient"],
  "désert": ["desert"],
  "eglise": ["church"],
  "escada": ["stairs"],
  "escalera": ["stairs"],
  "escalier": ["stairs"],
  "escritorio": ["office"],
  "escritório": ["office"],
  "escuro": ["dark"],
  "estacao": ["station"],
  "estacion": ["station"],
  "estación": ["station"],
  "estação": ["station"],
  "estrada": ["road"],
  "estrela": ["star"],
  "estrella": ["star"],
  "estrellas": ["star"],
  "estudio": ["studio"],
  "estúdio": ["studio"],
  "etoile": ["star"],
  "fajar": ["sunrise"],
  "falaise": ["cliff"],
  "faro": ["lighthouse"],
  "farol": ["lighthouse"],
  "feld": ["field"],
  "fiore": ["flower"],
  "fiume": ["river"],
  "fleur": ["flower"],
  "fleuve": ["river"],
  "flor": ["flower"],
  "flores": ["flower"],
  "floresta": ["forest"],
  "fluss": ["river"],
  "fonce": ["dark"],
  "foncé": ["dark"],
  "foresta": ["forest"],
  "foret": ["forest"],
  "forêt": ["forest"],
  "gach": ["brick"],
  "gare": ["station"],
  "garten": ["garden"],
  "gebirge": ["mountain"],
  "gece": ["night"],
  "gecis": ["gradient"],
  "geel": ["yellow"],
  "gelap": ["dark"],
  "gelb": ["yellow"],
  "geleira": ["glacier"],
  "gereja": ["church"],
  "geçiş": ["gradient"],
  "ghiacciaio": ["glacier"],
  "giallo": ["yellow"],
  "giardino": ["garden"],
  "glaciar": ["glacier"],
  "glacier": ["glacier"],
  "glasier": ["glacier"],
  "gletscher": ["glacier"],
  "gletser": ["glacier"],
  "gletsjer": ["glacier"],
  "go": ["wood"],
  "gokyuzu": ["sky"],
  "gol": ["lake"],
  "gorden": ["curtain"],
  "gordijn": ["curtain"],
  "gradasi": ["gradient"],
  "gradiente": ["gradient"],
  "grau": ["grey"],
  "gri": ["grey"],
  "grigio": ["grey"],
  "grijs": ["grey"],
  "gris": ["grey"],
  "groen": ["green"],
  "grot": ["cave"],
  "grotta": ["cave"],
  "grotte": ["cave"],
  "grun": ["green"],
  "grün": ["green"],
  "gua": ["cave"],
  "gun batimi": ["sunset"],
  "gun dogumu": ["sunrise"],
  "gunung": ["mountain"],
  "gunung berapi": ["volcano"],
  "gurun": ["desert"],
  "gökyüzü": ["sky"],
  "göl": ["lake"],
  "gün batımı": ["sunset"],
  "gün doğumu": ["sunrise"],
  "gạch": ["brick"],
  "gỗ": ["wood"],
  "habitacion": ["room"],
  "habitación": ["room"],
  "hafen": ["harbour"],
  "hai dang": ["lighthouse"],
  "hang": ["cave"],
  "haven": ["harbour"],
  "hell": ["light"],
  "hemel": ["sky"],
  "hijau": ["green"],
  "himmel": ["sky"],
  "hitam": ["black"],
  "ho": ["lake"],
  "hoa": ["flower"],
  "hoang hon": ["sunset"],
  "hohle": ["cave"],
  "holz": ["wood"],
  "hong": ["pink"],
  "hout": ["wood"],
  "hoàng hôn": ["sunset"],
  "hutan": ["forest"],
  "höhle": ["cave"],
  "hải đăng": ["lighthouse"],
  "hồ": ["lake"],
  "hồng": ["pink"],
  "iglesia": ["church"],
  "igreja": ["church"],
  "irmak": ["river"],
  "istana": ["castle"],
  "istasyon": ["station"],
  "jalan": ["road"],
  "jambatan": ["bridge"],
  "jardim": ["garden"],
  "jardin": ["garden"],
  "jardín": ["garden"],
  "jaune": ["yellow"],
  "jembatan": ["bridge"],
  "jingga": ["orange"],
  "kahverengi": ["brown"],
  "kain": ["fabric"],
  "kale": ["castle"],
  "kamar": ["room"],
  "kamar tidur": ["bedroom"],
  "kamer": ["room"],
  "kantoor": ["office"],
  "kantor": ["office"],
  "kar": ["snow"],
  "kasteel": ["castle"],
  "kastil": ["castle"],
  "kayu": ["wood"],
  "kebun": ["garden"],
  "kecerunan": ["gradient"],
  "kelabu": ["grey"],
  "kelas": ["classroom"],
  "kerk": ["church"],
  "ket cau": ["texture"],
  "keuken": ["kitchen"],
  "kilise": ["church"],
  "kirche": ["church"],
  "kirmizi": ["red"],
  "klaslokaal": ["classroom"],
  "klassenzimmer": ["classroom"],
  "klif": ["cliff"],
  "klippe": ["cliff"],
  "kopru": ["bridge"],
  "kota": ["city"],
  "koyu": ["dark"],
  "kubu": ["castle"],
  "kuche": ["kitchen"],
  "kuil": ["temple"],
  "kumas": ["fabric"],
  "kumaş": ["fabric"],
  "kuning": ["yellow"],
  "kutuphane": ["library"],
  "köprü": ["bridge"],
  "küche": ["kitchen"],
  "kütüphane": ["library"],
  "kırmızı": ["red"],
  "kết cấu": ["texture"],
  "lac": ["lake"],
  "ladang": ["field"],
  "ladrillo": ["brick"],
  "lago": ["lake"],
  "langit": ["sky"],
  "langsir": ["curtain"],
  "laranja": ["orange"],
  "lau dai": ["castle"],
  "laut": ["sea"],
  "legno": ["wood"],
  "lembah": ["valley"],
  "lembut": ["soft"],
  "leuchtturm": ["lighthouse"],
  "lever de soleil": ["sunrise"],
  "licht": ["light"],
  "lila": ["purple"],
  "liman": ["harbour"],
  "lop hoc": ["classroom"],
  "lucht": ["sky"],
  "lâu đài": ["castle"],
  "lớp học": ["classroom"],
  "madeira": ["wood"],
  "madera": ["wood"],
  "magara": ["cave"],
  "malam": ["night"],
  "mar": ["sea"],
  "marbre": ["marble"],
  "mare": ["sea"],
  "marmar": ["marble"],
  "marmer": ["marble"],
  "marmo": ["marble"],
  "marmol": ["marble"],
  "marmor": ["marble"],
  "marmore": ["marble"],
  "marrom": ["brown"],
  "marron": ["brown"],
  "marrone": ["brown"],
  "marrón": ["brown"],
  "masjid": ["mosque"],
  "matahari terbenam": ["sunset"],
  "matahari terbit": ["sunrise"],
  "mattone": ["brick"],
  "mauer": ["wall"],
  "mavi": ["blue"],
  "may": ["cloud"],
  "mağara": ["cave"],
  "meer": ["lake", "sea"],
  "mem": ["soft"],
  "mer": ["sea"],
  "merah": ["red"],
  "merah jambu": ["pink"],
  "merah muda": ["pink"],
  "mercusuar": ["lighthouse"],
  "merdiven": ["stairs"],
  "mermer": ["marble"],
  "mesquita": ["mosque"],
  "mezquita": ["mosque"],
  "montagna": ["mountain"],
  "montagne": ["mountain"],
  "montana": ["mountain"],
  "montanha": ["mountain"],
  "montaña": ["mountain"],
  "mor": ["purple"],
  "morado": ["purple"],
  "morbido": ["soft"],
  "moschea": ["mosque"],
  "moschee": ["mosque"],
  "moskee": ["mosque"],
  "mosquee": ["mosque"],
  "mosquée": ["mosque"],
  "mur": ["wall"],
  "muro": ["wall"],
  "musee": ["museum"],
  "museo": ["museum"],
  "museu": ["museum"],
  "museum": ["museum"],
  "musée": ["museum"],
  "mutfak": ["kitchen"],
  "muur": ["wall"],
  "muze": ["museum"],
  "muzium": ["museum"],
  "mármol": ["marble"],
  "mármore": ["marble"],
  "mây": ["cloud"],
  "müze": ["museum"],
  "mềm": ["soft"],
  "nacht": ["night"],
  "naranja": ["orange"],
  "nascer do sol": ["sunrise"],
  "nau": ["brown"],
  "negro": ["black"],
  "nehir": ["river"],
  "neige": ["snow"],
  "nero": ["black"],
  "neve": ["snow"],
  "nha bep": ["kitchen"],
  "nha ga": ["station"],
  "nha tho": ["church"],
  "nha tho hoi giao": ["mosque"],
  "nhà bếp": ["kitchen"],
  "nhà ga": ["station"],
  "nhà thờ": ["church"],
  "nieve": ["snow"],
  "noche": ["night"],
  "noir": ["black"],
  "noite": ["night"],
  "notte": ["night"],
  "nuage": ["cloud"],
  "nube": ["cloud"],
  "nubes": ["cloud"],
  "nui": ["mountain"],
  "nui lua": ["volcano"],
  "nuit": ["night"],
  "nuvem": ["cloud"],
  "nuvola": ["cloud"],
  "nâu": ["brown"],
  "núi": ["mountain"],
  "núi lửa": ["volcano"],
  "oda": ["room"],
  "oficina": ["office"],
  "ofis": ["office"],
  "orange": ["orange"],
  "oranje": ["orange"],
  "oranye": ["orange"],
  "orman": ["forest"],
  "oscuro": ["dark"],
  "paars": ["purple"],
  "padang": ["field"],
  "padang pasir": ["desert"],
  "pantai": ["beach"],
  "parc": ["park"],
  "parco": ["park"],
  "pared": ["wall"],
  "parede": ["wall"],
  "parete": ["wall"],
  "park": ["park"],
  "parque": ["park"],
  "pedra": ["stone"],
  "pegunungan": ["mountain"],
  "pejabat": ["office"],
  "pelabuhan": ["harbour"],
  "pembe": ["pink"],
  "penhasco": ["cliff"],
  "perang": ["brown"],
  "perde": ["curtain"],
  "perpustakaan": ["library"],
  "phare": ["lighthouse"],
  "phong": ["room"],
  "phong ngu": ["bedroom"],
  "phòng": ["room"],
  "phòng ngủ": ["bedroom"],
  "piece": ["room"],
  "piedra": ["stone"],
  "pierre": ["stone"],
  "pietra": ["stone"],
  "pink": ["pink"],
  "pièce": ["room"],
  "plage": ["beach"],
  "plaj": ["beach"],
  "playa": ["beach"],
  "pohon": ["tree"],
  "pokok": ["tree"],
  "pont": ["bridge"],
  "ponte": ["bridge"],
  "por do sol": ["sunset"],
  "port": ["harbour"],
  "porto": ["harbour"],
  "praia": ["beach"],
  "preto": ["black"],
  "puente": ["bridge"],
  "puerto": ["harbour"],
  "puesta de sol": ["sunset"],
  "pura": ["temple"],
  "putih": ["white"],
  "pôr do sol": ["sunset"],
  "quarto": ["bedroom", "room"],
  "raum": ["room"],
  "rem": ["curtain"],
  "rideau": ["curtain"],
  "rio": ["river"],
  "rivier": ["river"],
  "riviere": ["river"],
  "rivière": ["river"],
  "rojo": ["red"],
  "rood": ["red"],
  "rosa": ["pink"],
  "rose": ["pink"],
  "rosso": ["red"],
  "rot": ["red"],
  "rouge": ["red"],
  "route": ["road"],
  "roxo": ["purple"],
  "roze": ["pink"],
  "ruang": ["room"],
  "ruang kelas": ["classroom"],
  "ruangan": ["room"],
  "rumah api": ["lighthouse"],
  "rung": ["forest"],
  "rèm": ["curtain"],
  "río": ["river"],
  "rừng": ["forest"],
  "sa mac": ["desert"],
  "sa mạc": ["desert"],
  "sahil": ["beach"],
  "sala": ["room"],
  "sala de aula": ["classroom"],
  "salji": ["snow"],
  "salju": ["snow"],
  "salle": ["room"],
  "salle de classe": ["classroom"],
  "sanft": ["soft"],
  "sang": ["light"],
  "sao": ["star"],
  "sari": ["yellow"],
  "sarı": ["yellow"],
  "sawah": ["field"],
  "scala": ["stairs"],
  "schlafzimmer": ["bedroom"],
  "schloss": ["castle"],
  "schnee": ["snow"],
  "schwarz": ["black"],
  "scogliera": ["cliff"],
  "scuro": ["dark"],
  "see": ["lake"],
  "sehir": ["city"],
  "selale": ["waterfall"],
  "senja": ["sunset"],
  "sinif": ["classroom"],
  "siyah": ["black"],
  "slaapkamer": ["bedroom"],
  "sneeuw": ["snow"],
  "sombre": ["dark"],
  "song": ["river"],
  "song bang": ["glacier"],
  "sonnenaufgang": ["sunrise"],
  "sonnenuntergang": ["sunset"],
  "spiaggia": ["beach"],
  "stad": ["city"],
  "stadt": ["city"],
  "stanza": ["room"],
  "stasiun": ["station"],
  "station": ["station"],
  "stazione": ["station"],
  "steen": ["stone"],
  "stein": ["stone"],
  "stella": ["star"],
  "ster": ["star"],
  "stern": ["star"],
  "sterne": ["star"],
  "stesen": ["station"],
  "stof": ["fabric"],
  "stoff": ["fabric"],
  "strada": ["road"],
  "strand": ["beach"],
  "strasse": ["road"],
  "straße": ["road"],
  "studio": ["studio"],
  "studyo": ["studio"],
  "stüdyo": ["studio"],
  "suave": ["soft"],
  "sungai": ["river"],
  "sáng": ["light"],
  "sông": ["river"],
  "sông băng": ["glacier"],
  "sınıf": ["classroom"],
  "tal": ["valley"],
  "taman": ["garden", "park"],
  "taman kota": ["park"],
  "tangga": ["stairs"],
  "tapinak": ["temple"],
  "tapınak": ["temple"],
  "tarla": ["field"],
  "tas": ["stone"],
  "tasik": ["lake"],
  "taş": ["stone"],
  "tebing": ["cliff"],
  "tecido": ["fabric"],
  "tekstur": ["texture"],
  "tela": ["fabric"],
  "tembok": ["wall"],
  "tempel": ["temple"],
  "tempio": ["temple"],
  "temple": ["temple"],
  "templo": ["temple"],
  "tenda": ["curtain"],
  "terang": ["light"],
  "tessuto": ["fabric"],
  "textur": ["texture"],
  "textura": ["texture"],
  "texture": ["texture"],
  "textuur": ["texture"],
  "thac": ["waterfall"],
  "thanh pho": ["city"],
  "thu vien": ["library"],
  "thung lung": ["valley"],
  "thung lũng": ["valley"],
  "thành phố": ["city"],
  "thác": ["waterfall"],
  "thư viện": ["library"],
  "tijolo": ["brick"],
  "tim": ["purple"],
  "tirai": ["curtain"],
  "tissu": ["fabric"],
  "toi": ["dark"],
  "trama": ["texture"],
  "tramonto": ["sunset"],
  "trang": ["white"],
  "trap": ["stairs"],
  "tre": ["bamboo"],
  "treppe": ["stairs"],
  "trắng": ["white"],
  "tugla": ["brick"],
  "tuin": ["garden"],
  "tuong": ["wall"],
  "turuncu": ["orange"],
  "tuyet": ["snow"],
  "tuyết": ["snow"],
  "tuğla": ["brick"],
  "tím": ["purple"],
  "tường": ["wall"],
  "tối": ["dark"],
  "ucurum": ["cliff"],
  "ufficio": ["office"],
  "ungu": ["purple"],
  "uçurum": ["cliff"],
  "vach da": ["cliff"],
  "vadi": ["valley"],
  "vai": ["fabric"],
  "vale": ["valley"],
  "valle": ["valley"],
  "vallee": ["valley"],
  "vallei": ["valley"],
  "vallée": ["valley"],
  "van phong": ["office"],
  "vang": ["yellow"],
  "veld": ["field"],
  "verde": ["green"],
  "verlauf": ["gradient"],
  "verloop": ["gradient"],
  "vermelho": ["red"],
  "vert": ["green"],
  "ville": ["city"],
  "viola": ["purple"],
  "violet": ["purple"],
  "violeta": ["purple"],
  "violett": ["purple"],
  "volcan": ["volcano"],
  "volcán": ["volcano"],
  "vorhang": ["curtain"],
  "vulcano": ["volcano"],
  "vulcao": ["volcano"],
  "vulcão": ["volcano"],
  "vulkaan": ["volcano"],
  "vulkan": ["volcano"],
  "vuon": ["garden"],
  "vuurtoren": ["lighthouse"],
  "vàng": ["yellow"],
  "vách đá": ["cliff"],
  "văn phòng": ["office"],
  "vườn": ["garden"],
  "vải": ["fabric"],
  "wald": ["forest"],
  "wand": ["wall"],
  "wasserfall": ["waterfall"],
  "waterval": ["waterfall"],
  "weg": ["road"],
  "weich": ["soft"],
  "weiss": ["white"],
  "weiß": ["white"],
  "wit": ["white"],
  "woestijn": ["desert"],
  "wolk": ["cloud"],
  "wolke": ["cloud"],
  "wolken": ["cloud"],
  "wuste": ["desert"],
  "wüste": ["desert"],
  "xam": ["grey"],
  "xanh duong": ["blue"],
  "xanh dương": ["blue"],
  "xanh la": ["green"],
  "xanh lá": ["green"],
  "xám": ["grey"],
  "yanardag": ["volcano"],
  "yanardağ": ["volcano"],
  "yatak odasi": ["bedroom"],
  "yatak odası": ["bedroom"],
  "yesil": ["green"],
  "yeşil": ["green"],
  "yildiz": ["star"],
  "yol": ["road"],
  "yumusak": ["soft"],
  "yumuşak": ["soft"],
  "yıldız": ["star"],
  "zacht": ["soft"],
  "zee": ["sea"],
  "ziegel": ["brick"],
  "zimmer": ["room"],
  "zonsondergang": ["sunset"],
  "zonsopgang": ["sunrise"],
  "zwart": ["black"],
  "árbol": ["tree"],
  "árvore": ["tree"],
  "çiçek": ["flower"],
  "çöl": ["desert"],
  "église": ["church"],
  "étoile": ["star"],
  "đen": ["black"],
  "đá": ["stone"],
  "đá cẩm thạch": ["marble"],
  "đêm": ["night"],
  "đường": ["road"],
  "đền": ["temple"],
  "đỏ": ["red"],
  "şehir": ["city"],
  "şelale": ["waterfall"],
  "бамбук": ["bamboo"],
  "белый": ["white"],
  "библиотека": ["library"],
  "водопад": ["waterfall"],
  "вокзал": ["station"],
  "вулкан": ["volcano"],
  "гавань": ["harbour"],
  "голубой": ["blue"],
  "гора": ["mountain"],
  "город": ["city"],
  "горы": ["mountain"],
  "градиент": ["gradient"],
  "дерево": ["tree"],
  "долина": ["valley"],
  "дорога": ["road"],
  "древесина": ["wood"],
  "жёлтый": ["yellow"],
  "закат": ["sunset"],
  "замок": ["castle"],
  "занавес": ["curtain"],
  "звезда": ["star"],
  "звёзды": ["star"],
  "зелёный": ["green"],
  "камень": ["stone"],
  "кирпич": ["brick"],
  "класс": ["classroom"],
  "комната": ["room"],
  "коричневый": ["brown"],
  "красный": ["red"],
  "кухня": ["kitchen"],
  "ледник": ["glacier"],
  "лес": ["forest"],
  "лестница": ["stairs"],
  "маяк": ["lighthouse"],
  "мечеть": ["mosque"],
  "море": ["sea"],
  "мост": ["bridge"],
  "мрамор": ["marble"],
  "музей": ["museum"],
  "мягкий": ["soft"],
  "небо": ["sky"],
  "ночь": ["night"],
  "облака": ["cloud"],
  "облако": ["cloud"],
  "озеро": ["lake"],
  "оранжевый": ["orange"],
  "офис": ["office"],
  "парк": ["park"],
  "пещера": ["cave"],
  "пляж": ["beach"],
  "поле": ["field"],
  "порт": ["harbour"],
  "пустыня": ["desert"],
  "рассвет": ["sunrise"],
  "река": ["river"],
  "розовый": ["pink"],
  "сад": ["garden"],
  "светлый": ["light"],
  "серый": ["grey"],
  "синий": ["blue"],
  "скала": ["cliff"],
  "снег": ["snow"],
  "спальня": ["bedroom"],
  "станция": ["station"],
  "стена": ["wall"],
  "студия": ["studio"],
  "текстура": ["texture"],
  "ткань": ["fabric"],
  "тёмный": ["dark"],
  "утёс": ["cliff"],
  "фиолетовый": ["purple"],
  "храм": ["temple"],
  "цветок": ["flower"],
  "цветы": ["flower"],
  "церковь": ["church"],
  "чёрный": ["black"],
  "штора": ["curtain"],
  "أبيض": ["white"],
  "أحمر": ["red"],
  "أخضر": ["green"],
  "أزرق": ["blue"],
  "أسود": ["black"],
  "أصفر": ["yellow"],
  "استوديو": ["studio"],
  "بحر": ["sea"],
  "بحيرة": ["lake"],
  "برتقالي": ["orange"],
  "بركان": ["volcano"],
  "بنفسجي": ["purple"],
  "بني": ["brown"],
  "تدرج": ["gradient"],
  "ثلج": ["snow"],
  "جبل": ["mountain"],
  "جدار": ["wall"],
  "جرف": ["cliff"],
  "جسر": ["bridge"],
  "حائط": ["wall"],
  "حجر": ["stone"],
  "حديقة": ["garden"],
  "حديقة عامة": ["park"],
  "حقل": ["field"],
  "خشب": ["wood"],
  "خيزران": ["bamboo"],
  "داكن": ["dark"],
  "درج": ["stairs"],
  "رخام": ["marble"],
  "رمادي": ["grey"],
  "زهرة": ["flower"],
  "ستارة": ["curtain"],
  "سحاب": ["cloud"],
  "سماء": ["sky"],
  "شاطئ": ["beach"],
  "شجرة": ["tree"],
  "شروق": ["sunrise"],
  "شلال": ["waterfall"],
  "صحراء": ["desert"],
  "طريق": ["road"],
  "طوب": ["brick"],
  "غابة": ["forest"],
  "غرفة": ["room"],
  "غرفة نوم": ["bedroom"],
  "غروب": ["sunset"],
  "غيوم": ["cloud"],
  "فاتح": ["light"],
  "فصل دراسي": ["classroom"],
  "قلعة": ["castle"],
  "قماش": ["fabric"],
  "كنيسة": ["church"],
  "كهف": ["cave"],
  "ليل": ["night"],
  "متحف": ["museum"],
  "محطة": ["station"],
  "مدينة": ["city"],
  "مسجد": ["mosque"],
  "مطبخ": ["kitchen"],
  "معبد": ["temple"],
  "مكتب": ["office"],
  "مكتبة": ["library"],
  "ملمس": ["texture"],
  "منارة": ["lighthouse"],
  "ميناء": ["harbour"],
  "ناعم": ["soft"],
  "نجم": ["star"],
  "نجوم": ["star"],
  "نهر": ["river"],
  "نهر جليدي": ["glacier"],
  "وادي": ["valley"],
  "ورد": ["flower"],
  "وردي": ["pink"],
  "आकाश": ["sky"],
  "ईंट": ["brick"],
  "ऑफिस": ["office"],
  "कक्षा": ["classroom"],
  "कपड़ा": ["fabric"],
  "कमरा": ["room"],
  "कार्यालय": ["office"],
  "काला": ["black"],
  "किला": ["castle"],
  "खेत": ["field"],
  "गहरा": ["dark"],
  "गिरजाघर": ["church"],
  "गुफा": ["cave"],
  "गुलाबी": ["pink"],
  "ग्रेडिएंट": ["gradient"],
  "ग्लेशियर": ["glacier"],
  "घाटी": ["valley"],
  "चट्टान": ["cliff"],
  "जंगल": ["forest"],
  "ज्वालामुखी": ["volcano"],
  "झरना": ["waterfall"],
  "झील": ["lake"],
  "तारा": ["star"],
  "दीवार": ["wall"],
  "धूसर": ["grey"],
  "नदी": ["river"],
  "नारंगी": ["orange"],
  "नीला": ["blue"],
  "पत्थर": ["stone"],
  "परदा": ["curtain"],
  "पहाड़": ["mountain"],
  "पार्क": ["park"],
  "पीला": ["yellow"],
  "पुल": ["bridge"],
  "पुस्तकालय": ["library"],
  "पेड़": ["tree"],
  "प्रकाशस्तंभ": ["lighthouse"],
  "फूल": ["flower"],
  "बंदरगाह": ["harbour"],
  "बगीचा": ["garden"],
  "बनावट": ["texture"],
  "बर्फ": ["snow"],
  "बांस": ["bamboo"],
  "बादल": ["cloud"],
  "बैंगनी": ["purple"],
  "भूरा": ["brown"],
  "मंदिर": ["temple"],
  "मस्जिद": ["mosque"],
  "मुलायम": ["soft"],
  "रसोई": ["kitchen"],
  "रात": ["night"],
  "रेगिस्तान": ["desert"],
  "लकड़ी": ["wood"],
  "लाल": ["red"],
  "वन": ["forest"],
  "शयनकक्ष": ["bedroom"],
  "शहर": ["city"],
  "संगमरमर": ["marble"],
  "संग्रहालय": ["museum"],
  "सड़क": ["road"],
  "सफेद": ["white"],
  "समुद्र": ["sea"],
  "समुद्र तट": ["beach"],
  "सीढ़ी": ["stairs"],
  "सूर्यास्त": ["sunset"],
  "सूर्योदय": ["sunrise"],
  "स्टूडियो": ["studio"],
  "स्टेशन": ["station"],
  "हरा": ["green"],
  "हल्का": ["light"],
  "กลางคืน": ["night"],
  "กำแพง": ["wall"],
  "ขาว": ["white"],
  "ครัว": ["kitchen"],
  "คืน": ["night"],
  "ชมพู": ["pink"],
  "ชายหาด": ["beach"],
  "ดอกไม้": ["flower"],
  "ดาว": ["star"],
  "ดำ": ["black"],
  "ต้นไม้": ["tree"],
  "ถนน": ["road"],
  "ถ้ำ": ["cave"],
  "ทะเล": ["sea"],
  "ทะเลทราย": ["desert"],
  "ทะเลสาบ": ["lake"],
  "ทุ่ง": ["field"],
  "ทุ่งนา": ["field"],
  "ท่าเรือ": ["harbour"],
  "ท้องฟ้า": ["sky"],
  "ธารน้ำแข็ง": ["glacier"],
  "นุ่ม": ["soft"],
  "น้ำตก": ["waterfall"],
  "น้ำตาล": ["brown"],
  "น้ำเงิน": ["blue"],
  "บันได": ["stairs"],
  "ประภาคาร": ["lighthouse"],
  "ปราสาท": ["castle"],
  "ป่า": ["forest"],
  "ผนัง": ["wall"],
  "ผ้า": ["fabric"],
  "ผ้าม่าน": ["curtain"],
  "พระอาทิตย์ขึ้น": ["sunrise"],
  "พระอาทิตย์ตก": ["sunset"],
  "พิพิธภัณฑ์": ["museum"],
  "พื้นผิว": ["texture"],
  "ฟ้า": ["sky"],
  "ภูเขา": ["mountain"],
  "ภูเขาไฟ": ["volcano"],
  "มัสยิด": ["mosque"],
  "มืด": ["dark"],
  "ม่วง": ["purple"],
  "ม่าน": ["curtain"],
  "วัด": ["temple"],
  "สตูดิโอ": ["studio"],
  "สถานี": ["station"],
  "สวน": ["garden"],
  "สวนสาธารณะ": ["park"],
  "สว่าง": ["light"],
  "สะพาน": ["bridge"],
  "สำนักงาน": ["office"],
  "สีขาว": ["white"],
  "สีชมพู": ["pink"],
  "สีดำ": ["black"],
  "สีน้ำตาล": ["brown"],
  "สีฟ้า": ["blue"],
  "สีม่วง": ["purple"],
  "สีส้ม": ["orange"],
  "สีเขียว": ["green"],
  "สีเทา": ["grey"],
  "สีเหลือง": ["yellow"],
  "สีแดง": ["red"],
  "ส้ม": ["orange"],
  "หน้าผา": ["cliff"],
  "หาด": ["beach"],
  "หิน": ["stone"],
  "หินอ่อน": ["marble"],
  "หิมะ": ["snow"],
  "หุบเขา": ["valley"],
  "ห้อง": ["room"],
  "ห้องนอน": ["bedroom"],
  "ห้องสมุด": ["library"],
  "ห้องเรียน": ["classroom"],
  "ออฟฟิศ": ["office"],
  "อิฐ": ["brick"],
  "เขียว": ["green"],
  "เข้ม": ["dark"],
  "เทา": ["grey"],
  "เมฆ": ["cloud"],
  "เมือง": ["city"],
  "เหลือง": ["yellow"],
  "แดง": ["red"],
  "แม่น้ำ": ["river"],
  "โบสถ์": ["church"],
  "ไผ่": ["bamboo"],
  "ไม้": ["wood"],
  "ไล่สี": ["gradient"],
  "オフィス": ["office"],
  "オレンジ": ["orange"],
  "カーテン": ["curtain"],
  "キッチン": ["kitchen"],
  "グラデーション": ["gradient"],
  "グレー": ["grey"],
  "スタジオ": ["studio"],
  "テクスチャ": ["texture"],
  "ビーチ": ["beach"],
  "ピンク": ["pink"],
  "モスク": ["mosque"],
  "レンガ": ["brick"],
  "事務所": ["office"],
  "云": ["cloud"],
  "公园": ["park"],
  "公園": ["park"],
  "冰川": ["glacier"],
  "办公室": ["office"],
  "博物館": ["museum"],
  "博物馆": ["museum"],
  "卧室": ["bedroom"],
  "厨房": ["kitchen"],
  "台所": ["kitchen"],
  "図書館": ["library"],
  "图书馆": ["library"],
  "城": ["castle"],
  "城堡": ["castle"],
  "城市": ["city"],
  "墙": ["wall"],
  "壁": ["wall"],
  "夕日": ["sunset"],
  "夜": ["night"],
  "大理石": ["marble"],
  "天空": ["sky"],
  "寝室": ["bedroom"],
  "寺": ["temple"],
  "寺庙": ["temple"],
  "山": ["mountain"],
  "山谷": ["valley"],
  "崖": ["cliff"],
  "川": ["river"],
  "工作室": ["studio"],
  "布": ["fabric"],
  "布料": ["fabric"],
  "庭": ["garden"],
  "庭園": ["garden"],
  "悬崖": ["cliff"],
  "房间": ["room"],
  "教会": ["church"],
  "教堂": ["church"],
  "教室": ["classroom"],
  "日の出": ["sunrise"],
  "日出": ["sunrise"],
  "日没": ["sunset"],
  "日落": ["sunset"],
  "明るい": ["light"],
  "星": ["star"],
  "星星": ["star"],
  "暗い": ["dark"],
  "木": ["tree"],
  "木头": ["wood"],
  "木材": ["wood"],
  "柔らかい": ["soft"],
  "柔和": ["soft"],
  "树": ["tree"],
  "桃色": ["pink"],
  "桥": ["bridge"],
  "棕色": ["brown"],
  "森": ["forest"],
  "森林": ["forest"],
  "楼梯": ["stairs"],
  "橋": ["bridge"],
  "橙": ["orange"],
  "橙色": ["orange"],
  "氷河": ["glacier"],
  "江": ["river"],
  "沙漠": ["desert"],
  "河": ["river"],
  "洞穴": ["cave"],
  "洞窟": ["cave"],
  "浅": ["light"],
  "浜": ["beach"],
  "海": ["sea"],
  "海滩": ["beach"],
  "深": ["dark"],
  "清真寺": ["mosque"],
  "渐变": ["gradient"],
  "港": ["harbour"],
  "港口": ["harbour"],
  "湖": ["lake"],
  "滝": ["waterfall"],
  "瀑布": ["waterfall"],
  "火山": ["volcano"],
  "灯台": ["lighthouse"],
  "灯塔": ["lighthouse"],
  "灰色": ["grey"],
  "田野": ["field"],
  "畑": ["field"],
  "白": ["white"],
  "白色": ["white"],
  "石": ["stone"],
  "石头": ["stone"],
  "砂漠": ["desert"],
  "砖": ["brick"],
  "神殿": ["temple"],
  "空": ["sky"],
  "窗帘": ["curtain"],
  "竹": ["bamboo"],
  "粉色": ["pink"],
  "紫": ["purple"],
  "紫色": ["purple"],
  "緑": ["green"],
  "红色": ["red"],
  "纹理": ["texture"],
  "绿色": ["green"],
  "花": ["flower"],
  "花园": ["garden"],
  "茶色": ["brown"],
  "蓝色": ["blue"],
  "街": ["city"],
  "谷": ["valley"],
  "質感": ["texture"],
  "赤": ["red"],
  "车站": ["station"],
  "道": ["road"],
  "道路": ["road"],
  "部屋": ["room"],
  "都市": ["city"],
  "野原": ["field"],
  "階段": ["stairs"],
  "雪": ["snow"],
  "雲": ["cloud"],
  "青": ["blue"],
  "駅": ["station"],
  "黄色": ["yellow"],
  "黑色": ["black"],
  "黒": ["black"],
  "갈색": ["brown"],
  "강": ["river"],
  "검정": ["black"],
  "계곡": ["valley"],
  "계단": ["stairs"],
  "공원": ["park"],
  "교실": ["classroom"],
  "교회": ["church"],
  "구름": ["cloud"],
  "그라데이션": ["gradient"],
  "길": ["road"],
  "꽃": ["flower"],
  "나무": ["tree"],
  "노랑": ["yellow"],
  "노을": ["sunset"],
  "눈": ["snow"],
  "다리": ["bridge"],
  "대나무": ["bamboo"],
  "대리석": ["marble"],
  "도로": ["road"],
  "도서관": ["library"],
  "도시": ["city"],
  "돌": ["stone"],
  "동굴": ["cave"],
  "들판": ["field"],
  "등대": ["lighthouse"],
  "모스크": ["mosque"],
  "목재": ["wood"],
  "바다": ["sea"],
  "박물관": ["museum"],
  "밝은": ["light"],
  "밤": ["night"],
  "방": ["room"],
  "벽": ["wall"],
  "벽돌": ["brick"],
  "별": ["star"],
  "보라": ["purple"],
  "부드러운": ["soft"],
  "부엌": ["kitchen"],
  "분홍": ["pink"],
  "빙하": ["glacier"],
  "빨강": ["red"],
  "사막": ["desert"],
  "사무실": ["office"],
  "사원": ["temple"],
  "산": ["mountain"],
  "성": ["castle"],
  "숲": ["forest"],
  "스튜디오": ["studio"],
  "어두운": ["dark"],
  "역": ["station"],
  "일몰": ["sunset"],
  "일출": ["sunrise"],
  "절": ["temple"],
  "절벽": ["cliff"],
  "정원": ["garden"],
  "주방": ["kitchen"],
  "주황": ["orange"],
  "직물": ["fabric"],
  "질감": ["texture"],
  "천": ["fabric"],
  "초록": ["green"],
  "침실": ["bedroom"],
  "커튼": ["curtain"],
  "파랑": ["blue"],
  "폭포": ["waterfall"],
  "하늘": ["sky"],
  "항구": ["harbour"],
  "해변": ["beach"],
  "호수": ["lake"],
  "화산": ["volcano"],
  "회색": ["grey"],
  "흰색": ["white"],
};

/** Every English concept the table can produce. The fuzzy pass falls back
 *  to these when a typed word is close to one but not equal to it. */
export const CONCEPTS: readonly string[] = [
  "bamboo",
  "beach",
  "bedroom",
  "black",
  "blue",
  "brick",
  "bridge",
  "brown",
  "castle",
  "cave",
  "church",
  "city",
  "classroom",
  "cliff",
  "cloud",
  "curtain",
  "dark",
  "desert",
  "fabric",
  "field",
  "flower",
  "forest",
  "garden",
  "glacier",
  "gradient",
  "green",
  "grey",
  "harbour",
  "kitchen",
  "lake",
  "library",
  "light",
  "lighthouse",
  "marble",
  "mosque",
  "mountain",
  "museum",
  "night",
  "office",
  "orange",
  "park",
  "pink",
  "purple",
  "red",
  "river",
  "road",
  "room",
  "sea",
  "sky",
  "snow",
  "soft",
  "stairs",
  "star",
  "station",
  "stone",
  "studio",
  "sunrise",
  "sunset",
  "temple",
  "texture",
  "tree",
  "valley",
  "volcano",
  "wall",
  "waterfall",
  "white",
  "wood",
  "yellow",
];
